import time
import streamlit as st

from app.telemetry_manager import TelemetryManager
from app.failure_predictor import FailurePredictor


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Hindsight Incident Command Center",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ============================================================
# SESSION STATE
# ============================================================

if "telemetry_manager" not in st.session_state:
    st.session_state.telemetry_manager = TelemetryManager()

if "telemetry" not in st.session_state:
    st.session_state.telemetry = None

if "simulation_running" not in st.session_state:
    st.session_state.simulation_running = False

if "simulation_mode" not in st.session_state:
    st.session_state.simulation_mode = "healthy"

if "prediction" not in st.session_state:
    st.session_state.prediction = None

if "investigation_result" not in st.session_state:
    st.session_state.investigation_result = None


# ============================================================
# LOAD FAILURE PREDICTION MODEL
# ============================================================

try:
    predictor = FailurePredictor()
    predictor_available = True

except Exception as e:
    predictor = None
    predictor_available = False

    st.warning(
        f"Failure prediction model unavailable: {e}"
    )


# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:

    st.title("🧠 Hindsight")
    st.caption("Incident Command Center")

    st.divider()

    st.subheader("Architecture")

    st.markdown(
        """
        📡 **Live Telemetry**

        ↓

        🔮 **Failure Prediction**

        ↓

        🧠 **Hindsight Recall**

        ↓

        🤖 **GPT-OSS 120B**

        ↓

        🔍 **Root Cause Analysis**

        ↓

        👨‍🔧 **Human Review**

        ↓

        🧠 **Hindsight Learning**
        """
    )

    st.divider()

    st.subheader("AI Components")

    st.write("**Failure Prediction**")
    st.write("Calibrated Multiclass Random Forest")

    st.write("**Memory**")
    st.write("Hindsight")

    st.write("**Reasoning**")
    st.write("GPT-OSS 120B")

    st.divider()

    st.subheader("Failure Classes")

    st.write("• Database Connection Exhaustion")
    st.write("• CPU Saturation")
    st.write("• Memory Exhaustion")
    st.write("• API Availability Degradation")
    st.write("• Disk Exhaustion")
    st.write("• Network Degradation")
    st.write("• No Failure")


# ============================================================
# MAIN HEADER
# ============================================================

st.title("🧠 Hindsight Incident Command Center")

st.write(
    "AI-powered predictive incident response that learns "
    "from historical production incidents."
)

st.write(
    "Monitor system telemetry, predict failures before "
    "they occur, investigate incidents, and capture "
    "engineer-confirmed resolutions."
)


# ============================================================
# LIVE SYSTEM TELEMETRY
# ============================================================

st.header("📡 Live System Telemetry")

st.caption(
    "Prototype telemetry is generated by the simulation "
    "engine. In production, this can be connected to "
    "Prometheus, Grafana, cloud monitoring, or application "
    "metrics."
)


# ============================================================
# SIMULATION CONTROLS
# ============================================================

control1, control2, control3 = st.columns(
    [2.2, 2.2, 1],
    gap="large",
)


with control1:

    scenario = st.selectbox(
        "Simulation scenario",

        [
            "healthy",
            "database",
            "cpu",
            "memory",
            "network",
            "api",
        ],

        format_func=lambda x: {
            "healthy": "🟢 Healthy System",
            "database": "🔴 Database Failure",
            "cpu": "🔴 CPU Saturation",
            "memory": "🔴 Memory Exhaustion",
            "network": "🔴 Network Degradation",
            "api": "🔴 API Degradation",
        }[x],

        index=[
            "healthy",
            "database",
            "cpu",
            "memory",
            "network",
            "api",
        ].index(
            st.session_state.simulation_mode
        ),
    )


with control2:

    start_simulation = st.button(
        "▶ Start / Restart Simulation",
        type="primary",
        use_container_width=True,
    )


with control3:

    stop_simulation = st.button(
        "■ Stop",
        use_container_width=True,
    )


# ============================================================
# START SIMULATION
# ============================================================

if start_simulation:

    st.session_state.simulation_mode = scenario

    try:

        st.session_state.telemetry = (
            st.session_state.telemetry_manager.start(
                scenario
            )
        )

        st.session_state.simulation_running = True

        st.session_state.prediction = None

    except Exception as e:

        st.error(
            f"Unable to start simulation: {e}"
        )


# ============================================================
# STOP SIMULATION
# ============================================================

if stop_simulation:

    try:

        st.session_state.telemetry_manager.stop()

    except Exception:
        pass

    st.session_state.simulation_running = False


# ============================================================
# GET CURRENT TELEMETRY
# ============================================================

if st.session_state.simulation_running:

    try:

        sample = (
            st.session_state.telemetry_manager.next_sample()
        )

        if sample is not None:
            st.session_state.telemetry = sample

    except Exception as e:

        st.error(
            f"Telemetry error: {e}"
        )


telemetry = st.session_state.telemetry


# ============================================================
# CURRENT TELEMETRY
# ============================================================

if telemetry:

    st.divider()

    # --------------------------------------------------------
    # CENTERED TELEMETRY TITLE
    # --------------------------------------------------------

    st.markdown(
        """
        <div style="
            text-align:center;
            font-size:2rem;
            font-weight:700;
            margin-bottom:1.5rem;
        ">
            📊 Current Telemetry
        </div>
        """,
        unsafe_allow_html=True,
    )


    # --------------------------------------------------------
    # CENTER STREAMLIT METRICS
    # --------------------------------------------------------

    st.markdown(
        """
        <style>

        div[data-testid="stMetric"] {
            text-align: center !important;
            display: flex !important;
            flex-direction: column !important;
            align-items: center !important;
        }

        div[data-testid="stMetricLabel"] {
            justify-content: center !important;
            width: 100% !important;
        }

        div[data-testid="stMetricLabel"] p {
            text-align: center !important;
            width: 100% !important;
        }

        div[data-testid="stMetricValue"] {
            justify-content: center !important;
            width: 100% !important;
        }

        div[data-testid="stMetricValue"] > div {
            text-align: center !important;
            width: 100% !important;
        }

        </style>
        """,
        unsafe_allow_html=True,
    )


    # ========================================================
    # ROW 1
    # ========================================================

    col1, col2, col3, col4 = st.columns(
        4,
        gap="large",
    )


    with col1:

        st.metric(
            label="CPU",
            value=f"{telemetry.get('cpu_percent', 0):.1f}%",
        )


    with col2:

        st.metric(
            label="Memory",
            value=f"{telemetry.get('memory_percent', 0):.1f}%",
        )


    with col3:

        st.metric(
            label="Disk",
            value=f"{telemetry.get('disk_percent', 0):.1f}%",
        )


    with col4:

        st.metric(
            label="DB Pool Usage",
            value=f"{telemetry.get('db_pool_usage', 0):.1f}%",
        )


    # ========================================================
    # ROW 2
    # ========================================================

    col1, col2, col3, col4 = st.columns(
        4,
        gap="large",
    )


    with col1:

        st.metric(
            label="DB Connections",
            value=f"{telemetry.get('db_connections', 0):.1f}%",
        )


    with col2:

        st.metric(
            label="API Latency",
            value=f"{telemetry.get('api_latency_ms', 0):.0f} ms",
        )


    with col3:

        st.metric(
            label="Error Rate",
            value=f"{telemetry.get('error_rate', 0):.2f}%",
        )


    with col4:

        st.metric(
            label="Queue Depth",
            value=f"{telemetry.get('queue_depth', 0):.0f}",
        )


    # ========================================================
    # ROW 3
    # ========================================================

    col1, col2, col3 = st.columns(
        3,
        gap="large",
    )


    with col1:

        st.metric(
            label="Request Rate",
            value=f"{telemetry.get('request_rate', 0):.0f}/s",
        )


    with col2:

        st.metric(
            label="Network Latency",
            value=f"{telemetry.get('network_latency_ms', 0):.0f} ms",
        )


    with col3:

        st.metric(
            label="Traffic Growth",
            value=f"{telemetry.get('traffic_growth_percent', 0):.1f}%",
        )


# ============================================================
# FAILURE PREDICTION
# ============================================================

if telemetry and predictor_available:

    try:

        prediction = predictor.predict(
            telemetry
        )

        st.session_state.prediction = prediction

    except Exception:

        try:

            prediction = predictor.predict_failure(
                telemetry
            )

            st.session_state.prediction = prediction

        except Exception as e:

            st.session_state.prediction = None

            st.error(
                f"Failure prediction error: {e}"
            )


prediction = st.session_state.prediction


# ============================================================
# PREDICTIVE FAILURE INTELLIGENCE
# ============================================================

if prediction:

    st.divider()

    st.header(
        "🔮 Predictive Failure Intelligence"
    )


    risk = int(
        prediction.get(
            "failure_risk",
            0,
        )
    )


    risk_level = str(
        prediction.get(
            "risk_level",
            "LOW",
        )
    )


    predicted_failure = str(
        prediction.get(
            "predicted_failure",
            "No immediate failure predicted",
        )
    )


    failure_type = str(
        prediction.get(
            "predicted_failure_type",
            prediction.get(
                "failure_type",
                "No Failure",
            ),
        )
    )


    type_probability = float(
        prediction.get(
            "predicted_failure_probability",
            prediction.get(
                "type_probability",
                0,
            ),
        )
    )


    risk_window = str(
        prediction.get(
            "risk_window",
            "No immediate failure window detected",
        )
    )


    confidence = float(
        prediction.get(
            "prediction_confidence",
            0,
        )
    )


    model_name = str(
        prediction.get(
            "model",
            "Calibrated Multiclass Random Forest",
        )
    )


    # ========================================================
    # RISK SUMMARY
    # ========================================================

    col1, col2, col3 = st.columns(
        3,
        gap="large",
    )


    with col1:

        st.metric(
            "Failure Risk",
            f"{risk}%",
        )


    with col2:

        st.metric(
            "Risk Level",
            risk_level,
        )


    with col3:

        st.metric(
            "Prediction",
            predicted_failure,
        )


    st.write("Failure Risk")

    st.progress(
        max(
            0,
            min(
                100,
                risk,
            ),
        ) / 100
    )


    # ========================================================
    # PREDICTION DETAILS
    # ========================================================

    st.subheader(
        "Prediction Details"
    )


    col1, col2, col3 = st.columns(
        3,
        gap="large",
    )


    with col1:

        st.metric(
            "Risk Window",
            risk_window,
        )


    with col2:

        st.metric(
            "Prediction Confidence",
            f"{confidence:.2f}%",
        )


    with col3:

        st.metric(
            "Model",
            model_name,
        )


    # ========================================================
    # PREDICTED FAILURE TYPE
    # ========================================================

    st.subheader(
        "🎯 Predicted Failure Type"
    )


    col1, col2 = st.columns(
        2,
        gap="large",
    )


    with col1:

        st.metric(
            "Failure Type",
            failure_type,
        )


    with col2:

        st.metric(
            "Type Probability",
            f"{type_probability:.2f}%",
        )


    # ========================================================
    # FAILURE TYPE PROBABILITIES
    # ========================================================

    probabilities = prediction.get(
        "failure_type_probabilities",
        [],
    )


    if probabilities:

        st.subheader(
            "📊 Failure Type Probabilities"
        )


        for item in probabilities:

            name = item.get(
                "display_name",
                item.get(
                    "failure_type",
                    "Unknown",
                ),
            )


            probability = float(
                item.get(
                    "probability",
                    0,
                )
            )


            col1, col2 = st.columns(
                [5, 1]
            )


            with col1:

                st.write(
                    name
                )


            with col2:

                st.write(
                    f"{probability:.2f}%"
                )


            st.progress(
                max(
                    0,
                    min(
                        100,
                        probability,
                    ),
                ) / 100
            )


    # ========================================================
    # IMPORTANT RISK INDICATORS
    # ========================================================

    indicators = prediction.get(
        "important_indicators",
        prediction.get(
            "risk_indicators",
            [],
        ),
    )


    if indicators:

        st.subheader(
            "⚠️ Current Risk Indicators"
        )


        for indicator in indicators:

            if isinstance(
                indicator,
                dict,
            ):

                name = indicator.get(
                    "feature",
                    indicator.get(
                        "name",
                        "Unknown",
                    ),
                )


                value = indicator.get(
                    "value",
                    "",
                )


                severity = indicator.get(
                    "severity",
                    "",
                )


                if severity:

                    st.write(
                        f"**{name}:** {value} — "
                        f"**{severity}**"
                    )

                else:

                    st.write(
                        f"**{name}:** {value}"
                    )

            else:

                st.write(
                    f"• {indicator}"
                )


# ============================================================
# INCIDENT INVESTIGATION
# ============================================================

st.divider()

st.header(
    "🔍 Incident Investigation"
)


incident_text = st.text_area(

    "Incident Description",

    value=(
        "The Payment API is returning HTTP 503 errors. "
        "Database connections are timing out and the "
        "database connection pool is nearly full. "
        "API latency and error rate are increasing, "
        "and the request queue is growing."
    ),

    height=140,
)


if st.button(
    "🧠 Investigate Current System State",
    type="primary",
    use_container_width=True,
):

    if not incident_text.strip():

        st.warning(
            "Please enter an incident description."
        )

    else:

        try:

            from app.agent import IncidentResponseAgent

            agent = IncidentResponseAgent()


            with st.spinner(
                "Investigating incident with Hindsight and GPT-OSS 120B..."
            ):

                try:

                    result = agent.investigate(
                        incident_text,
                        telemetry,
                    )

                except TypeError:

                    result = agent.investigate(
                        incident_text,
                    )


            st.session_state.investigation_result = result


            try:
                agent.close()
            except Exception:
                pass


            st.success(
                "Incident investigation completed."
            )

            st.rerun()


        except Exception as e:

            st.error(
                f"Incident investigation failed: {e}"
            )

            st.exception(e)


# ============================================================
# INCIDENT RESPONSE ANALYSIS
# ============================================================

result = st.session_state.investigation_result


if result:

    st.divider()

    st.header(
        "🚨 Incident Response Analysis"
    )


    analysis = result.get(
        "analysis",
        result,
    )


    incident_id = result.get(
        "incident_id",
        "",
    )


    # ========================================================
    # INCIDENT OVERVIEW
    # ========================================================

    st.subheader(
        "Incident Overview"
    )


    col1, col2, col3, col4 = st.columns(
        4,
        gap="large",
    )


    with col1:

        st.metric(
            "Severity",
            str(
                analysis.get(
                    "severity",
                    "Unknown",
                )
            ),
        )


    with col2:

        st.metric(
            "Service",
            str(
                analysis.get(
                    "service",
                    "Unknown",
                )
            ),
        )


    with col3:

        st.metric(
            "Category",
            str(
                analysis.get(
                    "category",
                    "Unknown",
                )
            ),
        )


    with col4:

        st.metric(
            "AI Confidence",
            f"{analysis.get('confidence', 0)}%",
        )


    if incident_id:

        st.caption(
            f"Incident ID: {incident_id}"
        )


    # ========================================================
    # INCIDENT SUMMARY
    # ========================================================

    st.subheader(
        "📌 Incident Summary"
    )


    st.write(
        analysis.get(
            "incident_summary",
            "No summary available.",
        )
    )


    # ========================================================
    # ROOT CAUSE
    # ========================================================

    st.subheader(
        "🎯 Likely Root Cause"
    )


    st.write(
        analysis.get(
            "root_cause",
            "No root cause identified.",
        )
    )


    # ========================================================
    # ROOT CAUSE CONFIDENCE
    # ========================================================

    if "root_cause_confidence" in analysis:

        root_confidence = int(
            analysis.get(
                "root_cause_confidence",
                0,
            )
        )


        st.metric(
            "Root Cause Confidence",
            f"{root_confidence}%",
        )


    # ========================================================
    # HISTORICAL EVIDENCE
    # ========================================================

    st.subheader(
        "🧠 Historical Evidence"
    )


    historical = analysis.get(
        "historical_evidence",
        [],
    )


    if historical:

        for evidence in historical:

            if isinstance(
                evidence,
                dict,
            ):

                st.write(
                    evidence.get(
                        "incident",
                        str(evidence),
                    )
                )

                if evidence.get(
                    "relevance"
                ):

                    st.caption(
                        evidence[
                            "relevance"
                        ]
                    )

            else:

                st.write(
                    evidence
                )

    else:

        st.info(
            "No historical evidence available."
        )


    # ========================================================
    # IMMEDIATE ACTIONS
    # ========================================================

    st.subheader(
        "⚡ Immediate Actions"
    )


    actions = analysis.get(
        "recommended_actions",
        [],
    )


    if actions:

        for i, action in enumerate(
            actions,
            1,
        ):

            st.write(
                f"**{i}.** {action}"
            )

    else:

        st.write(
            "No immediate actions returned."
        )


    # ========================================================
    # SHORT TERM ACTIONS
    # ========================================================

    st.subheader(
        "🔧 Short-Term Actions"
    )


    actions = analysis.get(
        "short_term_actions",
        [],
    )


    if actions:

        for i, action in enumerate(
            actions,
            1,
        ):

            st.write(
                f"**{i}.** {action}"
            )

    else:

        st.write(
            "No short-term actions returned."
        )


    # ========================================================
    # LONG TERM PREVENTION
    # ========================================================

    st.subheader(
        "🛡️ Long-Term Prevention"
    )


    actions = analysis.get(
        "long_term_prevention",
        [],
    )


    if actions:

        for i, action in enumerate(
            actions,
            1,
        ):

            st.write(
                f"**{i}.** {action}"
            )

    else:

        st.write(
            "No long-term prevention actions returned."
        )


    # ========================================================
    # AI REASONING
    # ========================================================

    st.subheader(
        "🤖 AI Reasoning"
    )


    reasoning = analysis.get(
        "reasoning_summary",
        analysis.get(
            "reasoning",
            "No reasoning available.",
        ),
    )


    st.info(
        reasoning
    )


    # ========================================================
    # UNCERTAINTY
    # ========================================================

    st.subheader(
        "⚠️ Uncertainty"
    )


    st.warning(
        analysis.get(
            "uncertainty",
            "No uncertainty reported.",
        )
    )


    # ========================================================
    # ENGINEER / TECHNICIAN REVIEW
    # ========================================================

    st.divider()

    st.header(
        "🧑‍🔧 Engineer / Technician Review"
    )


    st.write(
        "The AI analysis is a recommendation. "
        "The engineer or technician should confirm "
        "what actually happened and record the real "
        "resolution."
    )


    helpful = st.radio(
        "Was the AI recommendation helpful?",
        [
            "Helpful",
            "Not Helpful",
        ],
        horizontal=True,
    )


    resolution = st.text_area(
        "What actually resolved the incident?",
        placeholder=(
            "Describe the actual fix performed by "
            "the technician or engineer..."
        ),
        height=130,
    )


    if st.button(
        "🧠 Save Technician Review",
        type="primary",
        use_container_width=True,
    ):

        if not resolution.strip():

            st.warning(
                "Please enter the actual resolution."
            )

        elif not incident_id:

            st.error(
                "Incident ID is missing."
            )

        else:

            try:

                from app.agent import IncidentResponseAgent

                review_agent = (
                    IncidentResponseAgent()
                )


                with st.spinner(
                    "Saving technician review and teaching Hindsight..."
                ):

                    review_agent.record_resolution(
                        incident_id=incident_id,
                        helpful=(
                            helpful == "Helpful"
                        ),
                        resolution=resolution,
                    )


                try:
                    review_agent.close()
                except Exception:
                    pass


                st.success(
                    "✅ Technician review saved. "
                    "Hindsight has learned from this incident."
                )


            except Exception as e:

                st.error(
                    f"Unable to save technician review: {e}"
                )

                st.exception(e)


# ============================================================
# INCIDENT HISTORY
# ============================================================

st.divider()

st.header(
    "📚 Incident Learning History"
)


try:

    from app.incident_history import IncidentHistory

    history_manager = IncidentHistory()

    history = history_manager.get_all()

except Exception as e:

    history = []

    st.warning(
        f"Unable to load incident history: {e}"
    )


if not history:

    st.info(
        "No incidents have been recorded yet."
    )

else:

    st.caption(
        f"{len(history)} incident(s) stored."
    )


    for record in reversed(history):

        incident_id_history = record.get(
            "incident_id",
            "",
        )

        severity = record.get(
            "severity",
            "UNKNOWN",
        )

        service = record.get(
            "service",
            "Unknown",
        )

        learned = record.get(
            "learned",
            False,
        )


        status = (
            "🧠 Learned"
            if learned
            else "⏳ Awaiting Review"
        )


        with st.expander(
            f"{status} • "
            f"{severity} • "
            f"{service}"
        ):

            st.write(
                f"**Incident ID:** "
                f"{incident_id_history}"
            )


            st.write(
                f"**Created:** "
                f"{record.get('created_at', '')}"
            )


            st.write(
                f"**Severity:** "
                f"{severity}"
            )


            st.write(
                f"**Service:** "
                f"{service}"
            )


            st.write(
                f"**Category:** "
                f"{record.get('category', 'Unknown')}"
            )


            st.subheader(
                "Original Incident"
            )


            st.write(
                record.get(
                    "incident",
                    "",
                )
            )


            st.subheader(
                "AI Suggested Root Cause"
            )


            st.write(
                record.get(
                    "root_cause",
                    "",
                )
            )


            st.write(
                f"**AI Confidence:** "
                f"{record.get('confidence', 0)}%"
            )


            feedback = record.get(
                "feedback",
                None,
            )


            if feedback:

                st.write(
                    f"**Technician Feedback:** "
                    f"{feedback}"
                )


            resolution = record.get(
                "resolution",
                None,
            )


            if resolution:

                st.subheader(
                    "🔧 Actual Resolution"
                )

                st.success(
                    resolution
                )


                st.write(
                    "🧠 This resolution has been "
                    "stored as organizational knowledge."
                )

            else:

                st.write(
                    "⏳ Waiting for technician-confirmed resolution."
                )


# ============================================================
# FOOTER
# ============================================================

st.divider()

st.caption(
    "Hindsight Incident Command Center • "
    "AI-assisted predictive incident response • "
    "Human review required for production actions"
)


# ============================================================
# AUTO REFRESH
# ============================================================

if st.session_state.simulation_running:

    time.sleep(1)

    st.rerun()